#!/bin/bash

# run processing jobs for 5km radar data -- takes about 30 minutes per year.
# for 1 km data will  takes ~ 100 times as long (larger data volume)
module load jaspy #load jaspy environment
export PYTHONPATH=$PYTHONPATH:$PWD
mkdir -p output # where output is going
years="2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022"
#years="2006 2007 2008 2009 2015 2016 2017 2018 2019"
#years="2004 2005 2006 2016" # years need to run again...
TIME="1:00:00"
RESOLN="5km"
#Q='short-serial'
Q='high-mem --mem=100000' # high mem q with a 100 GB of RAM
# for 1km data takes about 4 hours to process a year.
for year in $years
do
	export TMPDIR=scratch/$year
	mkdir -p $TMPDIR
	echo "Made $TMPDIR submitting job"
#	sbatch -p $Q --time=$TIME -o "output/process_radar_$RESOLN_$year.out" ./process_radar_data.py $year --verbose --monitor --resolution $RESOLN --nodaily --region 20500 659500 -74500 1000000
	sbatch -p $Q --time=$TIME -o "output/process_radar_$RESOLN_$year.out" ./process_radar_data.py $year --verbose --monitor --resolution $RESOLN --nodaily --region 280500 480500 684500 884500 --outdir summary_5km_1h --resample 15Min
done


