#!/bin/bash

# run processing jobs for 5km radar data -- takes about 30 minutes per year.
# for 1 km data will probably take ~ 100 times as long (larger data volume)
module load jaspy #load jaspy environment
export PYTHONPATH=$PYTHONPATH:$PWD
mkdir -p output # where output is going
years="2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022"
#years="2006 2007 2008 2009 2015 2016 2017 2018 2019"
#years="2004 2005 2006 2016" # years need to run again...
TIME="1:00:00"
RESOLN="5-km"
# 1km analysis
##TIME="12:00:00"
##RESOLN="1-km"
##years="2020 2021" 
for year in $years
do
	export TMPDIR=scratch/$year
	mkdir -p $TMPDIR
	echo "Made $TMPDIR submitting job"
	sbatch -p short-serial --time=$TIME -o "output/process_radar_$RESOLN_$year.out" ./process_radar_data.py $year --verbose --monitor --resolution $RESOLN
done


